<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CmcTs.Core\CmcTs.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>98a9d110-4fb5-4d3f-b35c-fca7dbb47590</UserSecretsId>
  </PropertyGroup>

</Project>
